import "./globals.css";
import { Inter } from "next/font/google";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import ToasterProvider from "./providers/ToasterProvider";
import ModalsContainer from "./components/ModalsContainer";
import getSession from "./lib/getSession";
import { useUsers } from "./hooks/useUsers";
import User from "./components/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen">
          <ReactQueryProvider>
            <ToasterProvider />
            <ModalsContainer />
            {children}
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
